services:  
  smartbill-app:  
    build: .  
    container_name: smartbill-app  
    restart: always  
    ports:  
      - 8001:8001  
    volumes:  
      - ./SmartBill:/app  
      - smartbill_vendor:/app/vendor  
    networks:  
      - shared-network

networks:
  shared-network:
    external: true
    name: shared-network

volumes:
  smartbill_vendor:
