services:  
  smartbill-app:  
    build: .  
    container_name: smartbill-app  
    restart: always  
    ports:  
      - 8001:8001  
    volumes:  
      - ./SmartBill:/app  
      - smartbill_vendor:/app/vendor  
    networks:  
      - dev-network  
volumes:  
  smartbill_vendor:  
networks:  
  dev-network:  
    external: true
    name: shared-services_dev-network
